### ISSUE TITLE
Error Codes 400 & 500

### ISSUE THREAD

**Issue by walefinancex** [UnUniFi/utils#195] opened 2022-02-08 23:06 UTC
I keep getting these error codes 400 and occasionally 500

**Comment by YasunoriMATSUOKA** [comment] 2022-02-10 09:16
@walefinancex 
Thank you for creating the issue.

1. In most cases, the cause of the error is either insufficient fees or an attempt to send a transaction that results in an insufficient CDP collateral ratio. Please try with checking them first.
2. If 1 does not solve your problem, please try to use one of the other node of the following nodes. (The b node tends to be unstable due to the concentration of access.)
  - http://a.test.ununifi.cauchye.net
  - http://b.test.ununifi.cauchye.net
3. If 1 and 2 does not solve your problem, please provide the following information to help us solve the problem.
  - Your address
  - Which transaction caused the problem? (ex. cdp create, deposit collateral, withdraw collateral, issue cdp, clear cdp, return coins to faucet or all etc.)
  - Your screenshot of the error
  - (If you can, Information displayed in the Console and Network of the browser's developer tools)

Thank you for your patience.

**Comment by walefinancex** [comment] 2022-02-10 10:37
Thank you, I have been able to complete the entire process.

**Comment by YasunoriMATSUOKA** [comment] 2022-02-10 10:42
@walefinancex 
Thank you! Then, I will close this issue.

**Closed by YasunoriMATSUOKA** 2022-02-10 10:42 UTC
